
    location @mediaserver {
        resolver 1.1.1.1;
        proxy_pass https://opendxp.my-demo.shop$request_uri;
        # proxy_set_header Authorization "Basic <base64-of-user:password>";
    }

    location ^~ /media/ {
        access_log off;
        expires max;
        try_files $uri @mediaserver;
    }

    location ^~ /thumbnail/ {
        access_log off;
        expires max;
        try_files $uri @mediaserver;
    }
