#ddev-generated
# If you remove the ddev-generated line above you
# are responsible for maintaining this file. DDEV will not then
# update it, for example if you add `additional_hostnames`, etc.

http:
  routers:
    swoofy-redis-commander-1358-http:
      entrypoints:
        - http-1358
      rule: HostRegexp(`^swoofy\.ddev\.site$`)
      
      service: "swoofy-redis-commander-1358"
      tls: false
      # middlewares:
      #   - "swoofy-redirectHttps"
    swoofy-web-80-http:
      entrypoints:
        - http-80
      rule: HostRegexp(`^swoofy\.ddev\.site$`)
      
      service: "swoofy-web-80"
      tls: false
      # middlewares:
      #   - "swoofy-redirectHttps"
    swoofy-web-8025-http:
      entrypoints:
        - http-8025
      rule: HostRegexp(`^swoofy\.ddev\.site$`)
      
      service: "swoofy-web-8025"
      tls: false
      # middlewares:
      #   - "swoofy-redirectHttps"
    swoofy-xhgui-80-http:
      entrypoints:
        - http-8143
      rule: HostRegexp(`^swoofy\.ddev\.site$`)
      
      service: "swoofy-xhgui-80"
      tls: false
      # middlewares:
      #   - "swoofy-redirectHttps"
    swoofy-elasticsearch-9200-http:
      entrypoints:
        - http-9200
      rule: HostRegexp(`^swoofy\.ddev\.site$`)
      
      service: "swoofy-elasticsearch-9200"
      tls: false
      # middlewares:
      #   - "swoofy-redirectHttps"
    swoofy-rabbitmq-15672-http:
      entrypoints:
        - http-15672
      rule: HostRegexp(`^swoofy\.ddev\.site$`)
      
      service: "swoofy-rabbitmq-15672"
      tls: false
      # middlewares:
      #   - "swoofy-redirectHttps"
    
    
    swoofy-redis-commander-1358-https:
      entrypoints:
        - http-1359
      rule: HostRegexp(`^swoofy\.ddev\.site$`)
      
      service: "swoofy-redis-commander-1358"
      
      tls: true
      
    
    
    swoofy-web-80-https:
      entrypoints:
        - http-443
      rule: HostRegexp(`^swoofy\.ddev\.site$`)
      
      service: "swoofy-web-80"
      
      tls: true
      
    swoofy-web-8025-https:
      entrypoints:
        - http-8026
      rule: HostRegexp(`^swoofy\.ddev\.site$`)
      
      service: "swoofy-web-8025"
      
      tls: true
      
    
    swoofy-xhgui-80-https:
      entrypoints:
        - http-8142
      rule: HostRegexp(`^swoofy\.ddev\.site$`)
      
      service: "swoofy-xhgui-80"
      
      tls: true
      
    
    swoofy-elasticsearch-9200-https:
      entrypoints:
        - http-9201
      rule: HostRegexp(`^swoofy\.ddev\.site$`)
      
      service: "swoofy-elasticsearch-9200"
      
      tls: true
      
    
    swoofy-rabbitmq-15672-https:
      entrypoints:
        - http-15673
      rule: HostRegexp(`^swoofy\.ddev\.site$`)
      
      service: "swoofy-rabbitmq-15672"
      
      tls: true
      
    

  middlewares:
    swoofy-redirectHttps:
      redirectScheme:
        scheme: https
        permanent: true

  services:
    swoofy-redis-commander-1358:
      loadbalancer:
        servers:
          - url: http://ddev-swoofy-redis-commander:1358
        
    
    swoofy-web-80:
      loadbalancer:
        servers:
          - url: http://ddev-swoofy-web:80
        
    swoofy-web-8025:
      loadbalancer:
        servers:
          - url: http://ddev-swoofy-web:8025
        
    
    
    swoofy-xhgui-80:
      loadbalancer:
        servers:
          - url: http://ddev-swoofy-xhgui:80
        
    
    swoofy-elasticsearch-9200:
      loadbalancer:
        servers:
          - url: http://ddev-swoofy-elasticsearch:9200
        
    
    swoofy-rabbitmq-15672:
      loadbalancer:
        servers:
          - url: http://ddev-swoofy-rabbitmq:15672
        
    
    

tls:
  certificates:
    - certFile: /mnt/ddev-global-cache/traefik/certs/swoofy.crt
      keyFile: /mnt/ddev-global-cache/traefik/certs/swoofy.key