#ddev-generated
# If you remove the ddev-generated line above you
# are responsible for maintaining this file. DDEV will not then
# update it, for example if you add `additional_hostnames`, etc.

http:
  routers:
    opendxp-elasticsearch-9200-http:
      entrypoints:
        - http-9200
      rule: HostRegexp(`^opendxp\.ddev\.site$`)
      
      service: "opendxp-elasticsearch-9200"
      tls: false
      # middlewares:
      #   - "opendxp-redirectHttps"
    opendxp-rabbitmq-15672-http:
      entrypoints:
        - http-15672
      rule: HostRegexp(`^opendxp\.ddev\.site$`)
      
      service: "opendxp-rabbitmq-15672"
      tls: false
      # middlewares:
      #   - "opendxp-redirectHttps"
    opendxp-redis-commander-1358-http:
      entrypoints:
        - http-1358
      rule: HostRegexp(`^opendxp\.ddev\.site$`)
      
      service: "opendxp-redis-commander-1358"
      tls: false
      # middlewares:
      #   - "opendxp-redirectHttps"
    opendxp-web-80-http:
      entrypoints:
        - http-80
      rule: HostRegexp(`^opendxp\.ddev\.site$`)
      
      service: "opendxp-web-80"
      tls: false
      # middlewares:
      #   - "opendxp-redirectHttps"
    opendxp-web-8025-http:
      entrypoints:
        - http-8025
      rule: HostRegexp(`^opendxp\.ddev\.site$`)
      
      service: "opendxp-web-8025"
      tls: false
      # middlewares:
      #   - "opendxp-redirectHttps"
    opendxp-web-9997-http:
      entrypoints:
        - http-8887
      rule: HostRegexp(`^opendxp\.ddev\.site$`)
      
      service: "opendxp-web-9997"
      tls: false
      # middlewares:
      #   - "opendxp-redirectHttps"
    opendxp-web-9998-http:
      entrypoints:
        - http-8888
      rule: HostRegexp(`^opendxp\.ddev\.site$`)
      
      service: "opendxp-web-9998"
      tls: false
      # middlewares:
      #   - "opendxp-redirectHttps"
    opendxp-web-9999-http:
      entrypoints:
        - http-8889
      rule: HostRegexp(`^opendxp\.ddev\.site$`)
      
      service: "opendxp-web-9999"
      tls: false
      # middlewares:
      #   - "opendxp-redirectHttps"
    opendxp-xhgui-80-http:
      entrypoints:
        - http-8143
      rule: HostRegexp(`^opendxp\.ddev\.site$`)
      
      service: "opendxp-xhgui-80"
      tls: false
      # middlewares:
      #   - "opendxp-redirectHttps"
    
    
    opendxp-elasticsearch-9200-https:
      entrypoints:
        - http-9201
      rule: HostRegexp(`^opendxp\.ddev\.site$`)
      
      service: "opendxp-elasticsearch-9200"
      
      tls: true
      
    
    opendxp-rabbitmq-15672-https:
      entrypoints:
        - http-15673
      rule: HostRegexp(`^opendxp\.ddev\.site$`)
      
      service: "opendxp-rabbitmq-15672"
      
      tls: true
      
    
    opendxp-redis-commander-1358-https:
      entrypoints:
        - http-1359
      rule: HostRegexp(`^opendxp\.ddev\.site$`)
      
      service: "opendxp-redis-commander-1358"
      
      tls: true
      
    
    
    
    
    
    opendxp-web-80-https:
      entrypoints:
        - http-443
      rule: HostRegexp(`^opendxp\.ddev\.site$`)
      
      service: "opendxp-web-80"
      
      tls: true
      
    opendxp-web-8025-https:
      entrypoints:
        - http-8026
      rule: HostRegexp(`^opendxp\.ddev\.site$`)
      
      service: "opendxp-web-8025"
      
      tls: true
      
    opendxp-web-9997-https:
      entrypoints:
        - http-9997
      rule: HostRegexp(`^opendxp\.ddev\.site$`)
      
      service: "opendxp-web-9997"
      
      tls: true
      
    opendxp-web-9998-https:
      entrypoints:
        - http-9998
      rule: HostRegexp(`^opendxp\.ddev\.site$`)
      
      service: "opendxp-web-9998"
      
      tls: true
      
    opendxp-web-9999-https:
      entrypoints:
        - http-9999
      rule: HostRegexp(`^opendxp\.ddev\.site$`)
      
      service: "opendxp-web-9999"
      
      tls: true
      
    
    opendxp-xhgui-80-https:
      entrypoints:
        - http-8142
      rule: HostRegexp(`^opendxp\.ddev\.site$`)
      
      service: "opendxp-xhgui-80"
      
      tls: true
      
    

  middlewares:
    opendxp-redirectHttps:
      redirectScheme:
        scheme: https
        permanent: true

  services:
    opendxp-elasticsearch-9200:
      loadbalancer:
        servers:
          - url: http://ddev-opendxp-elasticsearch:9200
        
    
    opendxp-rabbitmq-15672:
      loadbalancer:
        servers:
          - url: http://ddev-opendxp-rabbitmq:15672
        
    
    opendxp-redis-commander-1358:
      loadbalancer:
        servers:
          - url: http://ddev-opendxp-redis-commander:1358
        
    
    opendxp-web-80:
      loadbalancer:
        servers:
          - url: http://ddev-opendxp-web:80
        
    opendxp-web-8025:
      loadbalancer:
        servers:
          - url: http://ddev-opendxp-web:8025
        
    opendxp-web-9997:
      loadbalancer:
        servers:
          - url: http://ddev-opendxp-web:9997
        
    opendxp-web-9998:
      loadbalancer:
        servers:
          - url: http://ddev-opendxp-web:9998
        
    opendxp-web-9999:
      loadbalancer:
        servers:
          - url: http://ddev-opendxp-web:9999
        
    
    
    
    
    
    opendxp-xhgui-80:
      loadbalancer:
        servers:
          - url: http://ddev-opendxp-xhgui:80
        
    
    

tls:
  certificates:
    - certFile: /mnt/ddev-global-cache/traefik/certs/opendxp.crt
      keyFile: /mnt/ddev-global-cache/traefik/certs/opendxp.key