pimcore:
    assets:
        image:
            thumbnails:
                definitions:
                    TEST:
                        items: {  }
                        medias: {  }
                        name: TEST
                        description: ''
                        group: ''
                        format: SOURCE
                        quality: 85
                        highResolution: null
                        preserveColor: false
                        preserveMetaData: false
                        rasterizeSVG: false
                        downloadable: false
                        modificationDate: 1705486298
                        creationDate: 1705486298
                        preserveAnimation: false
