security:
    providers:
        opendxp_admin:
            id: OpenDxp\Security\User\UserProvider

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        # OpenDXP WebDAV HTTP basic // DO NOT CHANGE!
        opendxp_webdav:
            pattern: ^/asset/webdav
            provider: opendxp_admin
            http_basic: ~

        # OpenDXP Admin Bundle firewall
        opendxp_admin: '%opendxp_admin_bundle.firewall_settings%'

    access_control:
        # OpenDXP admin ACl  // DO NOT CHANGE!
        - { path: ^/admin/settings/display-custom-logo, roles: PUBLIC_ACCESS }
        - { path: ^/admin/login/2fa-verify, roles: IS_AUTHENTICATED_2FA_IN_PROGRESS }
        - { path: ^/admin/login/2fa-setup, roles: ROLE_OPENDXP_USER }
        - { path: ^/admin/login/2fa, roles: IS_AUTHENTICATED_2FA_IN_PROGRESS }
        - { path: ^/admin/login$, roles: PUBLIC_ACCESS }
        - { path: ^/admin/login/(login|lostpassword|deeplink|csrf-token)$, roles: PUBLIC_ACCESS }
        - { path: ^/admin, roles: ROLE_OPENDXP_USER }
        - { path: ^/asset/webdav, roles: ROLE_OPENDXP_USER }

    role_hierarchy:
        # OpenDXP admin  // DO NOT CHANGE!
        ROLE_OPENDXP_ADMIN: [ROLE_OPENDXP_USER]
